### ISSUE TITLE
Distribute to containers

### ISSUE THREAD

**Issue by zmiklank** [sclorg/tfaga-wrapper#8]
- httpd-container https://github.com/sclorg/httpd-container/pull/177
- nginx-container https://github.com/sclorg/nginx-container/pull/235
- s2i-php-container https://github.com/sclorg/s2i-php-container/pull/398
- varnish-container https://github.com/sclorg/varnish-container/pull/118
- mariadb-container https://github.com/sclorg/mariadb-container/pull/199
- postgresql-container https://github.com/sclorg/postgresql-container/pull/500
- s2i-nodejs-container https://github.com/sclorg/s2i-nodejs-container/pull/383
- s2i-python-container https://github.com/sclorg/s2i-python-container/pull/589
- mysql-container https://github.com/sclorg/mysql-container/pull/337
- redis-container https://github.com/sclorg/redis-container/pull/140
- s2i-perl-container https://github.com/sclorg/s2i-perl-container/pull/267
- s2i-ruby-container https://github.com/sclorg/s2i-ruby-container/pull/464

**Comment by phracek** [comment]
List of supported scenarios.

container-tests:
- Fedora
- CentOS 7
- CentOS Stream 8
- CentOS Stream 9
- RHEL 7
- RHEL 8
- RHEL 9
- RHEL 9 - unsubscribed

OpenShift tests:
- CentOS 7 - OpenShift 3
- RHEL 7 - OpenShift 3
- RHEL 7 - OpenShift 4
- RHEL 8 - OpenShift 4
- RHEL 9 - OpenShift 4

**Comment by zmiklank** [comment]
I need to do some adjustments, as now the tests are ran also for OCP4 in CentOS7 compose.

Please do not continue with merging until I fix that.

**Comment by zmiklank** [comment]
The adjustments are now delivered to all of the PRs. Please feel free to continue with reviews.
